from html_similarity import *

#amazon
f1 = open("amazon_testfiles/am_n_login.htm", encoding="utf8")
s1 = f1.read()
f2 = open("amazon_testfiles/am_login.htm", encoding="utf8")
s2 = f2.read()
print('AMAZON:\n')
print('style similarity zelfde:',style_similarity(s1, s2))
print('structural similarity zelfde:',structural_similarity(s1, s2))
print('totale similarity zelfde:',similarity(s1, s2))
f3 = open("amazon_testfiles/am_anders.htm", encoding="utf8")
s3 = f3.read()
print('style similarity anders:',style_similarity(s1, s3))
print('structural similarity anders:',structural_similarity(s1, s3))
print('totale similarity anders:',similarity(s1, s3))
print('\n')

#bol
f1 = open("bol_testfiles/bol_ingelogd.htm", encoding="utf8")
s1 = f1.read()
f2 = open("bol_testfiles/bol_n_ingelogd.htm", encoding="utf8")
s2 = f2.read()
f3 = open("bol_testfiles/bol_anders.htm", encoding="utf8")
s3 = f3.read()
print('BOL:\n')
print('style similarity zelfde:',style_similarity(s1, s2))
print('structural similarity zelfde:',structural_similarity(s1, s2))
print('totale similarity zelfde:',similarity(s1, s2))
f3 = open("amazon_testfiles/am_anders.htm", encoding="utf8")
s3 = f3.read()
print('style similarity anders:',style_similarity(s1, s3))
print('structural similarity anders:',structural_similarity(s1, s3))
print('totale similarity anders:',similarity(s1, s3))
print('\n')

#youtube
f1 = open("yt_testfiles/yt_n_login.htm", encoding="utf8")
s1 = f1.read()
f2 = open("yt_testfiles/yt_login.htm", encoding="utf8")
s2 = f2.read()
f3 = open("yt_testfiles/yt_anders.htm", encoding="utf8")
s3 = f3.read()
print('YOUTUBE:\n')
print('style similarity zelfde:',style_similarity(s1, s2))
print('structural similarity zelfde:',structural_similarity(s1, s2))
print('totale similarity zelfde:',similarity(s1, s2))
f3 = open("amazon_testfiles/am_anders.htm", encoding="utf8")
s3 = f3.read()
print('style similarity anders:',style_similarity(s1, s3))
print('structural similarity anders:',structural_similarity(s1, s3))
print('totale similarity anders:',similarity(s1, s3))
